config/routes.rb
Rails.application.routes.draw do
  
  resources :portfolios, except: [:show]

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  
  # get 'blogs/:id/publish', to: 'blogs#toggle_status', as: 'blog_publish'

  resources :blogs do 
    member do 
      get 'publish', to: 'blogs#toggle_status'
    end 
  end 

  # get 'pages/home'

  # get 'pages/contact'

  get 'about', to: 'pages#about'

  get 'contact', to: 'pages#contact'

  root to: "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: [:draft, :published]
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
 
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:edit, :update, :destroy, :toggle_status]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.friendly.find(params[:id])
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
 
  def toggle_status
   ( @blog.draft?) ? @blog.published! : @blog.draft!
    
    redirect_to blogs_url, notice: 'Post has been updated!'
  end 

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @blogs = Blog.all
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :get_portfolio, only: [:show, :edit, :update, :destroy]

  def index 
    @portfolio_items = Portfolio.all
  end 

  def new 
    @portfolio_item = Portfolio.new 
  end 
  
  def show 
    
  end 

  def create
    @portfolio_item = Portfolio.new(portfolio_params)
    if @portfolio_item.save 
      flash[:notice] = 'Portfolio has been created successfully.'
      redirect_to @portfolio_item 
    else 
      flash.now[:error] = "Something went wrong."
      render 'new'
    end 
  end 
  
  def edit 
    
  end 

  def update 
    if @portfolio_item.update_attributes(portfolio_params)
      flash[:notice] = "Portfolio has been updated."
      redirect_to @portfolio_item
    else 
      flash[:error] = "Something went wrong."
      render 'new'
    end 

  end 

  def destroy 
    @portfolio_item.delete
    flash[:notice] = "Portfolio successfully deleted."
    redirect_to portfolios_url 
  end 

  private 
  
  def get_portfolio 
    @portfolio_item = Portfolio.find(params[:id])
  end 

  def portfolio_params 
    params.require(:portfolio).permit(:title, :subtitle, :body)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(title) 
    if title.empty? 
      "Rails Portfolio"
    else 
      "Rails Portfolio" + " | #{title}" 
    end 
  end 
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :blog_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% if blog.draft? %>
          <td><%= link_to 'Publish', publish_blog_path(blog.id) %></td>
        <% else %>
         <td><%= link_to 'Upublish', publish_blog_path(blog.id) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title(yield :head)%></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%=message_type%>"><%= message%></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<%= content_for :head do %>
  Home
<% end %>

<h1>Home</h1>
<ul>
  <% @blogs.each do |blog| %>
    <li><%= blog.title %></li>
  <% end %>
</ul>

app/views/portfolios/_form.html.erb
<%= form_with model: @portfolio_item do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portfolios/edit.html.erb
<%= content_for :head do %>
  Edit
<% end %>

<%= render "form" %>

app/views/portfolios/index.html.erb
<%= content_for :head do %>
  Portfolio
<% end %>

<h1>Portfolio</h1>
<button><%= link_to 'New Portfolio', new_portfolio_path %></button>

<% @portfolio_items.each do |portfolio_item|%>
  <div>
    <h3><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id) %></h3>
    <h3><%= portfolio_item.subtitle %></h3>
    <p><%= portfolio_item.body %></p>
    <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
    <div class="portfolio-buttons">
      <button class="btn btn-success"><%= link_to "Edit", edit_portfolio_path(portfolio_item.id) %></button>
      <button class="btn btn-success"><%= link_to "Delete", portfolio_path(portfolio_item.id), method: :delete %></button>
    </div>
  </div>
  
<% end %>

app/views/portfolios/new.html.erb
<%= content_for :head do %>
  New 
<% end %>

<%=  render 'form' %>

app/views/portfolios/show.html.erb
<%= content_for :head do %>

<% end %>
<div>
  <p><%= @portfolio_item.title %></p>
  <p><%= @portfolio_item.body %></p>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <%= "You have #{pluralize(object.errors.size, 'error')}"%>
  <div class="error-explanation">
    <% object.errors.full_message do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>
<% end %>